enableRobotsTXT: true
languageCode: en-us
params:
  twitter_link: https://www.twitter.com/polarisnatsec
  instagram_link: https://www.instagram.com/polarisnatsec/
  donate_link: https://secure.winred.com/polaris-national-security-pac/donate
  popup: ""
  popup_link: ""
  form_endpoint: https://usebasin.com/f/bc8c13289456
  form_endpoint_signup: https://usebasin.com/f/0df09d0343e3
  facebook_link: https://www.facebook.com/101769448776724
  paid_for: Paid for by Polaris Action Inc
  youtube_link: https://www.youtube.com/channel/UCtGcOmOrtHtPFyjdzwGGvpA
  twitter_user: polarisnatsec
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: false
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
taxonomies:
  category: categories
  tag: tags
  memorandum_category: memorandum_categories
  faqs_category: faqs_categories
  team_category: team_categories
  section_category: section_categories
title: Polaris National Security
baseURL: https://polaris-us.org
menu:
  main:
    - name: About Us
      url: /about
      weight: 5
    - name: Policy Focus
      url: /focus
      weight: 10
    - name: Updates
      url: /updates
      weight: 20
    - name: Media
      url: /media
      weight: 32
    - name: Past Events
      url: /events
      weight: 35
    - name: Contact
      url: /contact
      weight: 40
  footer:
    - name: Home
      url: /
      weight: 10
    - name: About Us
      url: /about
      weight: 15
    - name: Policy Focus
      url: /focus
      weight: 20
    - name: Updates
      url: /updates
      weight: 30
    - name: Media
      url: /media
      weight: 32
    - name: Past Events
      url: /events
      weight: 45
    - name: Contact
      url: /contact
      weight: 50
