baseURL:
languageCode: en-us
title: Polaris National Security
taxonomies:
  category: categories
  tag: tags
  memorandum_category: memorandum_categories
  accordion_category: accordion_categories
  team_category: team_categories
  section_category: section_categories
enableRobotsTXT: true
paginate: 1
params:
  twitter_user: kris_ray
  twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/
  youtube_link: https://www.youtube.com/
  #google_analytics: UA-
  paid_for: Paid for by Polaris National Security
  form_endpoint: 123456
  donate_link: /#
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
menu:
  main:
    - name: Our Focus
      url: /focus
      weight: 10
    - name: Updates
      url: /updates
      weight: 20
    - name: About
      url: /about
      weight: 30
    - name: Contact
      url: /contact
      weight: 40
  footer:
    - name: Home
      url: /
      weight: 10
    - name: Our Focus
      url: /focus
      weight: 20
    - name: Updates
      url: /updates
      weight: 30
    - name: About
      url: /about
      weight: 40
    - name: Contact
      url: /contact
      weight: 50