[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.141.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BUILD_DRAFTS = "false"
  HUGO_BUILD_FUTURE = "false"
  HUGO_BUILD_EXPIRED = "false"

[context.deploy-preview]
  command = "hugo --gc --buildFuture"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.141.0"
  HUGO_BUILD_DRAFTS = "true"
  HUGO_BUILD_EXPIRED = "false"

[context.branch-deploy]
  command = "hugo --gc --buildFuture"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.141.0"
  HUGO_BUILD_DRAFTS = "true"
  HUGO_BUILD_EXPIRED = "false"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"